### ISSUE TITLE
teamProjects class should check for valid parameters at init

### ISSUE THREAD

**Issue by chepix10** [fidmor89/TFS#1]
teamProjects class should check if its init method is receiving valid parameters. In the unit test it fails because even if you send it and empty string it returns the object. This could cause troubles when trying to connect to that specific team project as it may not have the url or GUI issues like no name for display.

**Comment by fidmor89** [comment]
Out of scope, wontfix.
This object is built using information received from the API call, we have to assume the call give us valid information.

**Comment by fidmor89** [comment]
It seems that it is a good idea to reopen this bug @chirislash  please take a look a it.

**Comment by fidmor89** [comment]
@chepix10 please test changes and close this issue if fixes are verified
