### ISSUE TITLE
password should not be hardcoded

### ISSUE THREAD

**Issue by fidmor89** [fidmor89/TFS#2]
keychain and login view must be implemented, meanwhile hardcoded password and user was used, but those credentials will be erased today after the demo.

Add a configuration file not synced to github or implement login so the app can still be used.
File must contain base url, user and password.

**Comment by fidmor89** [comment]
this seems an easy way to go: https://github.com/kishikawakatsumi/KeychainAccess

To install using cocoapods follow this instructions: https://github.com/kishikawakatsumi/KeychainAccess#swift-2.0-cocoapods

**Comment by chirislash** [comment]
The password is now passed by a secure text field and if the user want to keep logged in the user, password and base url is stored in keychain using Keychain Wrapper.
Keychain Wrapper got in this link https://github.com/jrendel/SwiftKeychainWrapper
